### ISSUE TITLE
Not working in windows ?

### ISSUE THREAD

**Issue by debelop13** [vjeux/download-file-sync#5]
Hi! 
In mac is working, but in windows it returns error for me:

Error: spawnSync curl ENOENT
    at exports._errnoException (util.js:1050:11)
    at spawnSync (child_process.js:471:20)
    at Object.execFileSync (child_process.js:508:13)
    at Object.module.(anonymous function) [as execFileSync] (ELECTRON_ASAR.js:173:20)
    at module.exports (C:\Users\debelop\Documents\Code\example\node_modules\download-file-sync\index.js:3:6)

Thanks!

**Comment by ogomez92** [comment]
Was this ever fixed?
It isn't working on windows for me either!
Any hints?
I tried npm install curl but no.
